[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheel]
packages = ["src/penguin"]
[project]
name = "penguin-agent-package"
version = "0.1.0"
description = "Simple, minimalistic AI-Agent for Linux that runs on almost every device"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
authors = [
  { name="theobalduser", email="fzierenberg@icloud.com" },
]
dependencies = [
  "animation>=0.0.7",
  "annotated-types>=0.8.0",
  "anyio>=4.15.1",
  "certifi>=2026.7.22",
  "ghostprint>=2.0.0",
  "h11>=0.16.0",
  "httpcore>=1.0.9",
  "httpx>=0.28.1",
  "idna>=3.20",
  "ollama>=0.6.2",
  "prompt_toolkit>=3.0.53",
  "pychalk>=2.0.1",
  "pydantic>=2.13.5",
  "pydantic_core>=2.46.5",
  "six>=1.17.0",
  "typing-inspection>=0.4.4",
  "typing_extensions>=4.16.0",
  "wcwidth>=0.9.1",
  "dotenv>=1.2.4"
]
